// components/Navbar.vue
<template>
  <header ref="navRef" class="fixed top-0 inset-x-0 z-50 bg-white/70 backdrop-blur-md border-b border-aerospace-sky opacity-0">
    <div class="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
      <NuxtLink to="/" class="font-semibold tracking-tight text-aerospace-navy text-xl">
        KD<span class="text-aerospace-accent">•</span>Portfolio
      </NuxtLink>
      
      <nav class="hidden md:flex gap-6 text-sm font-medium text-aerospace-text">
        <a href="#about" class="hover:text-aerospace-accent transition-colors">About</a>
        <a href="#skills" class="hover:text-aerospace-accent transition-colors">Skills</a>
        <a href="#projects" class="hover:text-aerospace-accent transition-colors">Projects</a>
        <a href="#contact" class="hover:text-aerospace-accent transition-colors">Contact</a>
      </nav>

      <button class="md:hidden text-aerospace-navy" aria-label="Open menu" @click="isOpen = !isOpen">
        <Menu />
      </button>
    </div>

    <!-- Mobile Menu -->
    <div v-if="isOpen" class="md:hidden px-4 pb-4 space-y-2 bg-white border-t border-aerospace-sky">
      <a href="#about" class="block py-2 text-aerospace-text">About</a>
      <a href="#skills" class="block py-2 text-aerospace-text">Skills</a>
      <a href="#projects" class="block py-2 text-aerospace-text">Projects</a>
      <a href="#contact" class="block py-2 text-aerospace-text">Contact</a>
    </div>
  </header>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { Menu } from 'lucide-vue-next';
import anime from 'animejs';

const isOpen = ref(false);
const navRef = ref(null);

onMounted(() => {
  anime({
    targets: navRef.value,
    translateY: [-20, 0],
    opacity: [0, 1],
    duration: 1000,
    easing: 'easeOutExpo',
    delay: 100
  });
});
</script>

// components/Navbar.jsx
'use client';

import { Menu } from 'lucide-react';
import { useState } from 'react';
import Link from 'next/link';

export default function Navbar() {
  const [open, setOpen] = useState(false);
  return (
    <header className="fixed top-0 inset-x-0 z-50 bg-slate-950/60 backdrop-blur border-b border-white/10">
      <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
        <Link href="#" className="font-semibold tracking-tight">KD<span className="text-sky-400">•</span>Portfolio</Link>
        <nav className="hidden md:flex gap-6 text-sm">
          <a href="#about" className="hover:text-sky-300">About</a>
          <a href="#skills" className="hover:text-sky-300">Skills</a>
          <a href="#projects" className="hover:text-sky-300">Projects</a>
          <a href="#contact" className="hover:text-sky-300">Contact</a>
        </nav>
        <button className="md:hidden" aria-label="Open menu" onClick={() => setOpen(!open)}>
          <Menu />
        </button>
      </div>
      {open && (
        <div className="md:hidden px-4 pb-4 space-y-2">
          <a href="#about" className="block">About</a>
          <a href="#skills" className="block">Skills</a>
          <a href="#projects" className="block">Projects</a>
          <a href="#contact" className="block">Contact</a>
        </div>
      )}
    </header>
  );
}
