// components/ProjectCard.vue
<template>
  <a
    :href="link"
    target="_blank"
    rel="noreferrer"
    ref="cardRef"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
    class="block rounded-2xl p-6 bg-white/60 backdrop-blur-sm border border-aerospace-sky shadow-lg shadow-aerospace-sky/50 transition-colors"
  >
    <div class="flex items-start justify-between gap-4">
      <div>
        <h3 class="text-lg font-semibold text-aerospace-navy">{{ title }}</h3>
        <p class="text-sm text-aerospace-text mt-1">{{ summary }}</p>
      </div>
    </div>
    <div class="mt-4 flex flex-wrap gap-2">
      <span v-for="tag in tags" :key="tag" class="text-xs px-2 py-1 rounded-full bg-aerospace-sky text-aerospace-accent font-medium">
        {{ tag }}
      </span>
    </div>
  </a>
</template>

<script setup>
import { ref } from 'vue';
import anime from 'animejs';

defineProps({
  title: String,
  summary: String,
  tags: Array,
  link: String
});

const cardRef = ref(null);

const handleMouseEnter = () => {
  anime({
    targets: cardRef.value,
    scale: 1.02,
    boxShadow: '0 10px 30px -10px rgba(14, 165, 233, 0.4)', // Bright Sky Blue Shadow
    duration: 300,
    easing: 'easeOutQuad'
  });
};

const handleMouseLeave = () => {
  anime({
    targets: cardRef.value,
    scale: 1,
    boxShadow: '0 4px 6px -1px rgba(224, 242, 254, 0.5)', // Reset to soft sky shadow
    duration: 300,
    easing: 'easeOutQuad'
  });
};
</script>

// components/ProjectCard.jsx
'use client';

import { motion } from 'framer-motion';

export default function ProjectCard({ title, summary, tags, link }) {
  return (
    <motion.a
      href={link}
      target="_blank"
      rel="noreferrer"
      className="card block hover:scale-[1.01] transition-transform"
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
    >
      <div className="flex items-start justify-between gap-4">
        <div>
          <h3 className="text-lg font-semibold">{title}</h3>
          <p className="text-sm text-slate-300 mt-1">{summary}</p>
        </div>
      </div>
      <div className="mt-4 flex flex-wrap gap-2">
        {tags.map((t) => (
          <span key={t} className="text-xs px-2 py-1 rounded-full bg-slate-800 ring-1 ring-white/10">{t}</span>
        ))}
      </div>
    </motion.a>
  );
}
